language: cpp
compiler:
    - gcc
env: BUILD=cmake CPP11=ON
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y cpputest
  - pip install --user cpp-coveralls
addons:
  apt:
    packages:
    - cmake
    - yasm
    - lcov
script: "./travisbuild.sh"
after_success:
  - echo "finished"
notifications:
  email:
    recipients:
      - info@alinous.org
