language: cpp
compiler:
    - gcc
env: BUILD=cmake CPP11=ON
os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - cmake
      - yasm
      - lcov
    env: BUILD_SYSTEM=cmake C_COMPILER=gcc CXX_COMPILER=g++
before_install:
  - export CC="gcc-4.9"
  - export CXX="g++-4.9"
  - sudo apt-get -qq update
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y cpputest
  - pip install --user cpp-coveralls
script: ./travisbuild.sh
after_success:
    - pushd target && ls -la && ./testall -v -gSchnorrTestGroup && popd
    - pushd target && make report && popd
    - coveralls --root . -E ".*/src_ext/*" -E ".*src_test*" -E "target" -E ".*CMakeFiles.*"
notifications:
  email:
    recipients:
      - info@alinous.org
