language: cpp
compiler:
    - gcc
env: BUILD=cmake CPP11=ON
os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
      - cmake
      - yasm
      - lcov
    env: BUILD_SYSTEM=cmake C_COMPILER=gcc-7 CXX_COMPILER=g++-7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y cpputest
  - sudo apt-get -qq install g++-7.3
  - pip install --user cpp-coveralls
script: ./travisbuild.sh
after_success:
    - pushd target && make test && popd
    - pushd target && make report && popd
    - coveralls --root . -E ".*/src_ext/*" -E ".*src_test*" -E "target" -E ".*CMakeFiles.*"
notifications:
  email:
    recipients:
      - info@alinous.org
