/* Generated By:JavaCC: Do not edit this line. AlinousLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGenCPP#start()
 */
#ifndef ALINOUSLANGCONSTANTS_H
#define ALINOUSLANGCONSTANTS_H
#include "JavaCC.h"

namespace alinouslang {
  /** End of File. */
const  int _EOF = 0;

  /** Lexical state. */
const  int DEFAULT = 0;

  /** Literal token values. */
  static const JJChar tokenImage_arr_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static const JJChar tokenImage_arr_1[] = 
{0x22, 0x20, 0x22, 0};
  static const JJChar tokenImage_arr_2[] = 
{0x22, 0x9, 0x22, 0};
  static const JJChar tokenImage_arr_3[] = 
{0x22, 0xa, 0x22, 0};
  static const JJChar tokenImage_arr_4[] = 
{0x22, 0xd, 0x22, 0};
  static const JJChar tokenImage_arr_5[] = 
{0x22, 0x61, 0x22, 0};
  static const JJChar tokenImage_arr_6[] = 
{0x22, 0x63, 0x22, 0};
  static const JJChar tokenImage_arr_7[] = 
{0x22, 0x62, 0x22, 0};
  static const JJChar* const tokenImage[] = {
tokenImage_arr_0, 
tokenImage_arr_1, 
tokenImage_arr_2, 
tokenImage_arr_3, 
tokenImage_arr_4, 
tokenImage_arr_5, 
tokenImage_arr_6, 
tokenImage_arr_7, 
  };

}
#endif
